### ISSUE TITLE
Add a new CSS Animation

### ISSUE THREAD

**Issue by Subho0710** [pranjay-poddar/Dev-Geeks#10]
**Describe the project you want to add with tech stack**

Adding a page loading animation using HTML and CSS

**Expected behavior**

Various moving objects including delivery box, air-plane and border

**Screenshots (optional)**

**Additional context (optional )**

**Comment by ilhamansari** [comment]
I want to do this issue.

**Comment by sumitbaroniya** [comment]
please assign me this issue

**Comment by Aanya9693** [comment]
Hey! Can you Assign this to me under Hacktoberfest? 

**Describe** : I'll be adding a **Sliding Text Animation**.

I'll be adding a page-loading animation using HTML and CSS

**Expected behaviour** : Text will be sliding one after another.

**Screenshot**
It'll look something like this
![image](https://user-images.githubusercontent.com/101557638/194694939-243e935d-0336-45b2-913d-3742b1f6f39f.png)

Please! Assign this to me

**Comment by UditSharma9999** [comment]
I would love to contribute to this open source project!
