### ISSUE TITLE
Recipe Book App 

### ISSUE THREAD

**Issue by Tusharjoshi1703** [pranjay-poddar/Dev-Geeks#1048]
**Describe the project you want to add with tech stack**

**Expected behavior**

**Screenshots (optional)**

**Additional context (optional )**

I will create a recipe book app which consists of recipes of various food items .
I will use Html, Css and JavaScript along with RecipeAPI to create it.
I was assigned this but by mistake I clicked on unassign , please assign it to me.

**Comment by divyapaneru** [comment]
project description
When the app loads, it will display a header with the title Recipe Book.
The main section of the app will be divided into two parts: the recipe list and the recipe details.
The recipe list will be displayed on the left side of the app and will show the names and descriptions of available recipes.
Each recipe item in the list will be clickable, and when clicked, it will display the selected recipe's details on the right side of the app.
The recipe details section will show the name and description of the selected recipe.
Initially, no recipe will be selected, and the recipe details section will be empty.
When a recipe item is clicked, it will become highlighted to indicate the selection.
Expected behavior
 I'll using HTML, CSS, and JavaScript to build the Recipe Book app. HTML will be used for the structure of the app, CSS for styling and layout, and JavaScript for dynamic functionality such as displaying the recipe details and handling user interactions.


please assign to me .
