### ISSUE TITLE
JavaScript Game 

### ISSUE THREAD

**Issue by Aarushijain-06** [pranjay-poddar/Dev-Geeks#1079]
**  Dear @prateekj7777 ,
 I want to request the addition of my JavaScript project to your repository. The project will be designed using Javascript, HTML, and CSS. This game will be like Mario ☺, please assign this issue to me.    **

**Comment by Gautam-10137** [comment]
Describe the project you want to add with tech stack

**Project Name**: Flying Eagle Game
**Project Description**:  It is a eagle flight game.In this game you have to save eagle from obstacles.You have to use (up,down,right,left) arrow keys of your keyboard. You will get 5 pts.  for each obstacle to save eagle.
**Tech Stack:** HTML , CSS & JS.

Expected behavior

**Benefits**: This application will makes users to have fun and increase their focus and increase their gaming ability.  
**Screenshot:** 
![flying eagle](https://github.com/pranjay-poddar/Dev-Geeks/assets/112772090/b2188c24-1222-4feb-bb29-b43850ab23cd)

**Additional**:
I have added sound effects in this application.Also more the time you spent, the speed of obstacle increase and it increase the hardness level.

**Comment by akshaysoni10** [comment]
Project you want to add with tech stack in **GSSOC' 23**

**Project Name** :- Dragon-Dino Game
**Description** :- It's dragon-dino game in which dino have to run and jump over the dragon. A user can use up, down, left and right arrow button to run the dino. Whenever a dino jumps over a dragon a score board is automatically increased by 1. If dino comes in contact with dragon then game over. I had added sound feature for better experience.
**Tech Stack** :- HTML, CSS, JS.
**Screenshot** :- 
![portfolio3](https://github.com/pranjay-poddar/Dev-Geeks/assets/109035961/f4908880-a036-43b9-934b-cc679065716e)
**Project Link** :- [https://dragon-dino-game.netlify.app/](url)

**Please assign it to me.**

**Comment by Gun2902** [comment]
can u assign me this isssue
