### ISSUE TITLE
Add moving car animation to animation css folder

### ISSUE THREAD

**Issue by Harshithardd** [pranjay-poddar/Dev-Geeks#1083]
Hey @pranjay-poddar  I am a contributor to GSSOC'23, an open-source project. I would like to add a moving car animation with a city background using html,css techstack  to the animation css folder.
Could you please assign this issue to me? I'm excited to contribute!

**Comment by UditSharma9999** [comment]
I would love to contribute to this open source project!

**Comment by Gautam-10137** [comment]
Describe the project you want to add with tech stack

**Project Name**:Add moving car animation
**Tech-Stac**k :  HTML,CSS.
**Project Description**: To create CSS animation effect. It will have a road moving animation and also moving building and moving car. It will be responsive.

Expected behavior
**Benefits**: It will create illusion to users that a car is actually moving.
Additonal:
I will also  add sound effects to this project.I have worked on lot of projects having CSS **Animation** effects.

Contributor: Gautam pahwa (GSSOC'23 contributor)

Please **assign** it to me!
