### ISSUE TITLE
A Realtime Chat Application Using NodeJs and SocketIO

### ISSUE THREAD

**Issue by ojKunal** [pranjay-poddar/Dev-Geeks#1100]
I want to add a Realtime Chat Application project (using NodeJs and SocketIO) under NodeJs Projects Folder.

**Comment by ojKunal** [comment]
I would like to work on this issue, please assign this issue to me under GSSoC'23.

**Comment by Gautam-10137** [comment]
Describe the project you want to add with tech stack

**Project Name**: A Realtime Chat Application
**Project Description**: It will allow users to communicate with each other in real time through text.This type of app allows for more immediate messaging than other types of communication such as email.
Tech Stack: NodeJs and SocketIO

Expected behavior

**Benefits:** This  application will makes it easy to communicate with people anywhere in the world by sending and receiving messages in real time.

Screenshot: This is screenshot of chat application I have made using **nodejs and firebase.**  I will made a app. using nodeJS and socketIO.
![chat room](https://github.com/pranjay-poddar/Dev-Geeks/assets/112772090/85ffc1bc-b73a-46ec-abc3-fe83c6f25f3f)

Additional : 
 Contributor : Gautam pahwa (GSSOC'23 contributor)
