### ISSUE TITLE
Add Drum Kit project to existing repository

### ISSUE THREAD

**Issue by sabhisharma-ise** [pranjay-poddar/Dev-Geeks#1102]
**Describe the project you want to add with tech stack**

Project Name: Drum Kit
Project Description: A simple drum kit that allows users to play different drum sounds.
Tech Stack: HTML, CSS, JS

**Expected behavior**

Benefits: The drum kit will allow users to practice their drumming skills and have fun. It will also be a simple and easy-to-use tool that can be used by anyone.

**Screenshots (optional)**

![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/100849696/4a0758c5-74d1-4e7e-aae0-f581489d169a)

**Additional context (optional )**

Contributor - Sabhi Sharma (GSSOC'23)

**Comment by harmeetsingh11** [comment]
Hi, I am a GSSoC'23 contributor. Can I work on this issue?

**Comment by Gautam-10137** [comment]
> **Describe the project you want to add with tech stack**
> 
> Project Name: Drum Kit Project Description: A simple drum kit that allows users to play different drum sounds. Tech Stack: HTML, CSS, JS
> 
> **Expected behavior**
> 
> Benefits: The drum kit will allow users to practice their drumming skills and have fun. It will also be a simple and easy-to-use tool that can be used by anyone.
> 
> **Screenshots (optional)**
> 
> ![image](https://user-images.githubusercontent.com/100849696/239705222-4a0758c5-74d1-4e7e-aae0-f581489d169a.png)
> 
> **Additional context (optional )**
> 
> Contributor - Sabhi Sharma (GSSOC'23)

Hii , I want to work on this project. Can you assign it to me?

**Comment by Gautam-10137** [comment]
Hii, I am contributor in GSSoC'23. Can you assign this to me?

**Comment by Gautam-10137** [comment]
Describe the project you want to add with tech stack

**Project Name**: Drum Kit
**Project Description**: A  drum kit that allows users to play different drum sounds  in the browser.
Tech Stack: HTML, CSS, JS

**Expected behavior**

Benefits: We all must have seen a drum kit in some concert or elsewhere, it is a collection of drums, cymbals and other percussion instruments. The goal for this article to build a drum kit app that runs in the browser and that will also be a simple and easy-to-use tool that can be used by anyone.
**Screenshots** :
![drum kit](https://github.com/pranjay-poddar/Dev-Geeks/assets/112772090/71b8ddb5-12eb-4f0b-ab7b-3b20621136f1)

**Additional context **

Contributor - Gautam pahwa  (GSSOC'23)

**Comment by srushtikage** [comment]
Hi I'm GSSoC'23 Contributor, i would like to work on this project pls assign it to me.

**Comment by pranjay-poddar** [comment]
Project already present
