### ISSUE TITLE
tic-tac-toe game 

### ISSUE THREAD

**Issue by sadhana70** [pranjay-poddar/Dev-Geeks#1117]
**Describe the Feature you want to end**

A game using HTML, CSS and JavaScript. Please, assign me an issue.
**Expected behavior**

**Screenshots (optional)**

**Additional context (optional )**

**Comment by Gautam-10137** [comment]
Describe the Feature you want to end
        A **Tic-Tac-Toe**  game 
**Tech-stack used** : HTML, CSS and JavaScript. 
**Expected behavior**: Tic Tac Toe is a two-player game in which the objective is to take turns and mark the correct spaces in a  grid .One player uses noughts, and the opposing player uses crosses.It is a "zero-sum game". If both players play perfectly, the game ends in a draw.
And I made it responsive to have smooth flow. 

**Screenshots **
![tic tac toe](https://github.com/pranjay-poddar/Dev-Geeks/assets/112772090/5a21ca0e-528d-4c45-99f8-6743e5f02b18)

Additional context :
I also added **sound effect** ,**responsiveness** and **animated** gif  to have the better experience of user.

Contributor:  Gautam pahwa (GSSOC'23)

Please assign this to me!

**Comment by Kareen12** [comment]
Describe the Feature you want to end : Tic Tac Toe Game

A game using HTML, CSS and JavaScript.

Expected behavior : A Tic Tac Toe game will typically feature a grid-based game board where two players take turns placing their symbols (X or O) in empty cells. The game validates moves, checks for winning conditions (three symbols in a row), and detects draws when all cells are filled. It provides feedback to players, such as displaying the winner or notifying them of a draw. Players have the option to restart the game, clearing the board for a new round.

Screenshots:

![game_ss](https://github.com/pranjay-poddar/Dev-Geeks/assets/105985059/8faf8238-8681-44df-8db2-cfce58eb3dba)

![game_ss2](https://github.com/pranjay-poddar/Dev-Geeks/assets/105985059/6e0ad4d7-f343-485e-931f-5e5e7e8f7507)

 Please, assign this issue to me.

**Comment by pranjay-poddar** [comment]
Already added
