### ISSUE TITLE
Project : Student Enrollment form

### ISSUE THREAD

**Issue by SnigdhaP2022** [pranjay-poddar/Dev-Geeks#1138]
**Describe the Feature you want to end**

I would like 
1)add components on the front page in enrol section
2) Mark the sections as mandatory in order to enrol so that we can filter duplicate entries

**Expected behavior**

This way we can increase user experience and also makes the site more functional
**Screenshots (optional)**

<img width="1437" alt="Screenshot 2023-05-21 at 12 13 24 PM" src="https://github.com/pranjay-poddar/Dev-Geeks/assets/102572480/f3989653-943f-4ac7-922c-3243506a9141">

**Additional context (optional )**

I would like to contribute to this site under GSSOC'23 Contributor. @pranjay-poddar Please assign this to me.

**Comment by bhoomigupta1406** [comment]
Hey @SnigdhaP2022 , I would like to work on this project by using Html, Css. I'll add all the components on the front page in enrol section and will mark the sections as mandatory in order to enrol so that we can filter duplicate entries and it will help increase user experience.
I would like to contribute to this site under GSSOC'23 Contributor.
Thank you!

**Comment by dk172923** [comment]
I would like to work on this issue. Assign it to me
