### ISSUE TITLE
Arduino Projects

### ISSUE THREAD

**Issue by hashfx** [pranjay-poddar/Dev-Geeks#1408]
**Describe the project you want to add with tech stack**

Arduino Code for **Digital Clock**, **3 LEDs Pattern**, **Keypad Door Lock** which could run on Virtual Arduino Simulator **TinkerCad** also

**Expected behavior**

would be able to learn and implement code on Arduino (useful for IoT Projects)

**Screenshots (optional)**

<figcaption> Digital Door Lock </figcaption>
<img src = "https://user-images.githubusercontent.com/69109482/193748368-925043c7-4246-4e34-a557-27f9bc096da4.png" width="500" height="400" />

<figcaption> Digital Clock </figcaption>
<img src = "https://user-images.githubusercontent.com/69109482/193514098-b1f45ffc-69ab-4482-9b9d-adb24140fb05.png" width="600" height="400" />

**Additional context (optional )**

Under GSSOC' 23

**Comment by Gautam-10137** [comment]
Describe the project you want to add with tech stack

Arduino Code for ESP8266 and MAX30100(**Hearbeat** sensor)

Expected behavior:
It would be able to measure Heartbeat and Oxygen level and will show it  on serial monitor.

Screenshots :
![esp and max30100](https://github.com/pranjay-poddar/Dev-Geeks/assets/112772090/0e29ecbe-0af8-4213-acff-7d9976d504df)

Contributor: Gautam pahwa(GSSOC'23 contributor)

**Comment by hashfx** [comment]
@pranjay-poddar This issue isn't resolved yet. You had to assign me the issue.
