### ISSUE TITLE
Diesel Website 

### ISSUE THREAD

**Issue by RAHULBAWA777** [pranjay-poddar/Dev-Geeks#957]
**Describe the project you want to add with tech stack**
Diesel Website  - HTML CSS JS

**Expected behavior**
Diesel Website Clone with functionalities

**Screenshots (optional)**

**Additional context (optional )**

**Comment by NishantRajhans** [comment]
![Screenshot (13)](https://github.com/pranjay-poddar/Dev-Geeks/assets/100590061/0204a479-cc89-4749-b902-5fb8b4c29af1)
**Describe the project you want to add with tech stack**
 i will make the frontend home page of this website using tech stack HTML CSS JS
**Expected behavior**
all the animation which is present in the website will be their

**Comment by bleep123** [comment]
I would like to contribute to this issue. Can you please assign it to me.

**Comment by NishantRajhans** [comment]
@pranjay-poddar i want to connect to you ,can you please tell me where i can connect to you regarding this project doubt bhaiya

**Comment by Developer-Swati** [comment]
Hello @pranjay-poddar , I can also design home page of this website. Please assign it to me.
